server:
  port: 8001
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lkanthrao/ConfigData123
          search-paths: ConfigData1
          

  application:
    name: springclouldconfigserver